/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store;

import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author nUll
 */
public class CityView extends BaseView implements IAction {

    private JTable table;
    private CityTableModel model;
    private ArrayList<CityModel> cities;

    /**
     * Creates new form CityView
     *
     * @param user
     * @throws java.lang.Exception
     */
    public CityView(UserModel user) throws Exception {
        super(user);
        initComponents();
        updateInterfaceSelf();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("City");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CityView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CityView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CityView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CityView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CityView(null).setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void jButtonInsertAction(ActionEvent evt) {
        try {
            CityModel city = new CityModel();
            CityNew cityNew = new CityNew(this, rootPaneCheckingEnabled, user, city);
            cityNew.setVisible(true);
            if (cityNew.isClosed()) {
                CityController.setUpdateCity(Operation.INSERT, city);
                updateInterfaceSelf();

            }
        } catch (Exception ex) {
            Logger.getLogger(CityView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void jButtonUpdateAction(ActionEvent evt) {
        try {

            int row = table.getSelectedRow();
            
            CityModel city = model.getRow(row);

            CityUpdate cityUpdate = new CityUpdate(this, rootPaneCheckingEnabled, user, city);
            cityUpdate.setVisible(true);
            if (cityUpdate.isClosed()) {
                CityController.setUpdateCity(Operation.UPDATE, city);
                updateInterfaceSelf();

            }
        } catch (Exception ex) {
            Logger.getLogger(CityView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public void jButtonDeleteAction(ActionEvent evt) {
        int[] rows = table.getSelectedRows();
        for (int index : rows) {
            CityModel city = model.getRow(index);
            CityController.setUpdateCity(Operation.DELETE, city);
        }
        updateInterfaceSelf();
    }

    @Override
    public File aExport() {
        return null;
    }

    @Override
    public void aInsertText() {
        aChangedText();

    }

    @Override
    public void aRemovedText() {
        aChangedText();
    }

    @Override
    public void aChangedText() {
        String pattern = getTextSearch().getText();
        cities = CityController.getAllCityByLike(Operation.SEARCH, pattern);
        model = new CityTableModel(cities);
        table.setModel(model);
        table.revalidate();

    }

    private void refershTable(ArrayList<CityModel> cities) {

        model = new CityTableModel(cities);
        table.setModel(model);
        if (table.isEditing()) {
            table.revalidate();
        }
    }

    private void updateInterfaceSelf() {
        table = getTable();
        cities = CityController.getAllCity();
        refershTable(cities);
    }
}
