/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store;

import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author nUll
 */
public class ProductView extends BaseView implements IAction {

    private JTable table;
    private ProductTableModel model;

    /**
     * Creates new form ProductFrame
     */
    public ProductView(UserModel user) throws Exception {
        super(user);
        initComponents();
        updateInterfaceSelf();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductView(null).setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void updateInterfaceSelf() {
        table = getTable();
        ArrayList<ProductModel> products = ProductController.getAllproduct();
        refershTable(products);

    }

    @Override
    public void jButtonInsertAction(ActionEvent evt) {
        try {
            ProductModel product = new ProductModel();
            ProductNew productNew = new ProductNew(this, rootPaneCheckingEnabled, user, product);
            productNew.setVisible(true);
            if (productNew.isClosed()) {

                ProductController.setUpdate(Operation.INSERT, product);

                ArrayList<ProductModel> products = ProductController.getAllproduct();
                refershTable(products);

            }
        } catch (Exception ex) {
            Logger.getLogger(ProductView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public void jButtonUpdateAction(ActionEvent evt) {
        try {
            int index = table.getSelectedRow();
            ProductModel product = model.getRow(index);
            ProductUpdate productUpdate = new ProductUpdate(this, rootPaneCheckingEnabled, user, product);
            productUpdate.setVisible(true);
            if (productUpdate.isClosed()) {
                ProductController.setUpdate(Operation.UPDATE, product);

                ArrayList<ProductModel> products = ProductController.getAllproduct();
                refershTable(products);

            }

        } catch (Exception ex) {
            Logger.getLogger(ProductView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void jButtonDeleteAction(ActionEvent evt) {
        int[] rows = table.getSelectedRows();
        for (int row : rows) {
            ProductModel product = model.getRow(row);
            ProductController.setUpdate(Operation.DELETE, product);
        }
        ArrayList<ProductModel> products = ProductController.getAllproduct();
        refershTable(products);

    }

    @Override
    public File aExport() {
        return null;
    }

    @Override
    public void aInsertText() {
        aChangedText();

    }

    @Override
    public void aRemovedText() {
        updateInterfaceSelf();
    }

    @Override
    public void aChangedText() {

        String pattern = getTextSearch().getText();
        ArrayList<ProductModel> products = ProductController.getAllproductByLike(Operation.SEARCH, pattern);
        refershTable(products);
    }

    private void refershTable(ArrayList<ProductModel> list) {
        model = new ProductTableModel(list);
        table.setModel(model);
        table.revalidate();

    }

}
