/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store;

import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author null
 */
public class SupplierNew extends BaseDialog {

    private boolean closed;
    private SupplierModel supplier;
    private ArrayList<SupplierModel> supplierList;
    private BranchTableModel branchTableModel;
    private BranchModel selectedBranch = null;

    /**
     * Creates new form SuplierNew
     *
     * @param parent
     * @param modal
     * @param user
     * @throws java.lang.Exception
     */
    public SupplierNew(java.awt.Frame parent, boolean modal, UserModel user) throws Exception {
        super(parent, modal, user);
        initComponents();
        updateInterfaceSelf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldBranchName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxBanchCity = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBranchAddress = new javax.swing.JTextField();
        jButtonBranchAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldBranchSeach = new javax.swing.JTextField();
        jButtonBranchDelete = new javax.swing.JButton();
        jButtonBranchEdit = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBranch = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextFieldSupplierName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSupplierEmail = new javax.swing.JTextField();
        jTextFieldSupplierPhone = new javax.swing.JTextField();
        jButtonSupplierAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Branch"));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Name");
        jLabel4.setPreferredSize(new java.awt.Dimension(34, 21));

        jComboBoxBanchCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("City");
        jLabel5.setPreferredSize(new java.awt.Dimension(34, 21));

        jButtonBranchAdd.setText("add");
        jButtonBranchAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBranchAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBranchAddActionPerformed(evt);
            }
        });

        jLabel7.setText("Address");
        jLabel7.setPreferredSize(new java.awt.Dimension(34, 21));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldBranchAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxBanchCity, javax.swing.GroupLayout.Alignment.LEADING, 0, 653, Short.MAX_VALUE)
                    .addComponent(jTextFieldBranchName, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBranchAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonBranchAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxBanchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBranchAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBranchDelete.setText("delete");
        jButtonBranchDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBranchDeleteActionPerformed(evt);
            }
        });

        jButtonBranchEdit.setText("edit");
        jButtonBranchEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBranchEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButtonBranchEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBranchDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBranchSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldBranchSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonBranchDelete)
                .addComponent(jButtonBranchEdit))
        );

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableBranch);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier"));

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Name");

        jLabel2.setText("phone");

        jLabel3.setText("email");

        jButtonSupplierAdd.setText("add");
        jButtonSupplierAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSupplierAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupplierAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSupplierPhone)
                    .addComponent(jTextFieldSupplierName)
                    .addComponent(jTextFieldSupplierEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSupplierAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
            .addComponent(jButtonSupplierAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonSave.setText("save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("exit");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        aSave();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSupplierAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupplierAddActionPerformed
        aSupplierAdd();
    }//GEN-LAST:event_jButtonSupplierAddActionPerformed

    private void jButtonBranchAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBranchAddActionPerformed
        aBranchAdd();
    }//GEN-LAST:event_jButtonBranchAddActionPerformed

    private void jButtonBranchDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBranchDeleteActionPerformed
        aBranchDelete();
    }//GEN-LAST:event_jButtonBranchDeleteActionPerformed

    private void jButtonBranchEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBranchEditActionPerformed
        aBranchEdit();
    }//GEN-LAST:event_jButtonBranchEditActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        aCancel();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    SupplierNew dialog = new SupplierNew(new javax.swing.JFrame(), true, null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SupplierNew.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBranchAdd;
    private javax.swing.JButton jButtonBranchDelete;
    private javax.swing.JButton jButtonBranchEdit;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSupplierAdd;
    private javax.swing.JComboBox jComboBoxBanchCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableBranch;
    private javax.swing.JTextField jTextFieldBranchAddress;
    private javax.swing.JTextField jTextFieldBranchName;
    private javax.swing.JTextField jTextFieldBranchSeach;
    private javax.swing.JTextField jTextFieldSupplierEmail;
    private javax.swing.JTextField jTextFieldSupplierName;
    private javax.swing.JTextField jTextFieldSupplierPhone;
    // End of variables declaration//GEN-END:variables

    public void aSupplierAdd() {
        setSupplier(new SupplierModel());

        String name = getjTextFieldSupplierName().getText();
        String phone = getjTextFieldSupplierPhone().getText();
        String email = getjTextFieldSupplierEmail().getText();
        supplier.setName(name);
        supplier.setPhone(phone);
        supplier.setEmail(email);

        SupplierController.setUpdate(Operation.INSERT, supplier);
        getSupplierList().add(supplier);

        setClosed(true);//if want exit with supplier only, no branches

        setBranchTableModel(new BranchTableModel(new ArrayList<BranchModel>()));
        getjTableBranch().setModel(getBranchTableModel());

        toggleBranchPanel(getjPanel2(), true);

    }

    /**
     * @return the closed
     */
    public boolean isClosed() {
        return closed;
    }

    /**
     * @return the supplier
     */
    public ArrayList<SupplierModel> getSuppliers() {
        return getSupplierList();
    }

    public SupplierModel getSupplier() {
        return supplier;
    }

    private void aBranchAdd() {

        String branchName = getjTextFieldBranchName().getText();
        String branchAddress = getjTextFieldBranchAddress().getText();
        CityModel city = (CityModel) getjComboBoxBanchCity().getSelectedItem();
        BranchModel branch = new BranchModel(supplier, city, branchName, branchAddress);

        BranchController.setUpdateBranch(Operation.INSERT, branch);

        getBranchTableModel().addRow(branch);
        supplier.getBranchList().add(branch);

        refershBranchTable();
        refershBranchNewPanel();

    }

    private void aBranchDelete() {
        int[] rows = getjTableBranch().getSelectedRows();
        BranchModel branch = null;
        for (int i : rows) {
            branch = getBranchTableModel().getRow(i);
            BranchController.setUpdateBranch(Operation.DELETE, branch);
        }
        supplier.getBranchList().remove(branch);
        getBranchTableModel().removeRowFrom(rows.length);
        refershBranchTable();

    }

    private void aBranchEdit() {

        String text = getjButtonBranchEdit().getText();

        if (text.equals("edit")) {

            getjButtonBranchEdit().setText("update");

            int row = getjTableBranch().getSelectedRow();

            selectedBranch = getBranchTableModel().getRow(row);
            getjTextFieldBranchName().setText(selectedBranch.getName());
            getjTextFieldBranchAddress().setText(selectedBranch.getAddress());
            getjComboBoxBanchCity().setSelectedItem(selectedBranch.getCity());

            getBranchTableModel().removeRow(selectedBranch);
            supplier.getBranchList().remove(selectedBranch);

            refershBranchTable();
            toggleBranchButton(false);
            toggleSupplierPanel(false);

        } else if (text.equals("update")) {

            getjButtonBranchEdit().setText("edit");

            CityModel city = (CityModel) getjComboBoxBanchCity().getSelectedItem();
            String name = getjTextFieldBranchName().getText();
            String address = getjTextFieldBranchAddress().getText();
            selectedBranch.setName(name);
            selectedBranch.setAddress(address);
            selectedBranch.setCity(city);

            BranchController.setUpdateBranch(Operation.UPDATE, selectedBranch);

            //ArrayList<BranchModel> branches = BranchController.getAllBranch(supplier);
            branchTableModel = new BranchTableModel(supplier.getBranchList());
            supplier.getBranchList().add(selectedBranch);

            refershBranchTable();
            refershBranchNewPanel();

            toggleBranchButton(true);
            toggleSupplierPanel(true);

        }
    }

    public void toggleBranchPanel(JPanel containter, boolean status) {

        Component[] components = containter.getComponents();
        for (Component component : components) {
            try {
                JPanel panel = (JPanel) component;
                toggleBranchPanel((JPanel) component, status);

            } catch (Exception e) {
                component.setEnabled(status);
            }
        }

    }

    private void aCancel() {
        setClosed(false);
        this.dispose();
    }

    private void updateInterfaceSelf() {
        //init obj.
        setSupplierList(new ArrayList<SupplierModel>());

        ArrayList<CityModel> cities = CityController.getAllCity();
        DefaultComboBoxModel cityModel = new DefaultComboBoxModel();
        getjComboBoxBanchCity().setModel(cityModel);
        for (CityModel city : cities) {
            cityModel.addElement(city);
        }

        getjTextFieldBranchSeach().getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent de) {
                aTextChanged();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                aTextChanged();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                aTextChanged();
            }

        });

        toggleBranchPanel(getjPanel2(), false);
    }

    private void aTextChanged() {
        String pattern = getjTextFieldBranchSeach().getText();
        if (pattern == "") {
            setBranchTableModel(new BranchTableModel(supplier.getBranchList()));
            getjTable1().setModel(getBranchTableModel());
            refershBranchTable();

        } else {
            BranchTableModel newBranchTableModel = new BranchTableModel(new ArrayList<BranchModel>());

            for (BranchModel branch : supplier.getBranchList()) {
                if (branch.contains(pattern)) {
                    newBranchTableModel.addRow(branch);

                }
            }
            getjTableBranch().setModel(newBranchTableModel);
            refershBranchTable();
        }
    }

    private void aSave() {
        setClosed(true);
        this.dispose();
    }

    public void refershBranchTable() {

        getjTableBranch().revalidate();

    }

    private void refershBranchNewPanel() {
        Component[] coms = getjPanel4().getComponents();
        for (Component com : coms) {
            try {
                JTextField text = (JTextField) com;
                text.setText("");
            } catch (Exception e) {

            }
        }
    }

    private void toggleBranchButton(boolean status) {

        getjButtonBranchDelete().setEnabled(status);
        getjButtonBranchAdd().setEnabled(status);
    }

    /**
     * @return the supplierList
     */
    public ArrayList<SupplierModel> getSupplierList() {
        return supplierList;
    }

    /**
     * @return the branchTableModel
     */
    public BranchTableModel getBranchTableModel() {
        return branchTableModel;
    }

    /**
     * @return the jButtonBranchAdd
     */
    public javax.swing.JButton getjButtonBranchAdd() {
        return jButtonBranchAdd;
    }

    /**
     * @return the jButtonBranchDelete
     */
    public javax.swing.JButton getjButtonBranchDelete() {
        return jButtonBranchDelete;
    }

    /**
     * @return the jButtonBranchEdit
     */
    public javax.swing.JButton getjButtonBranchEdit() {
        return jButtonBranchEdit;
    }

    /**
     * @return the jButtonCancel
     */
    public javax.swing.JButton getjButtonCancel() {
        return jButtonCancel;
    }

    /**
     * @return the jButtonSave
     */
    public javax.swing.JButton getjButtonSave() {
        return jButtonSave;
    }

    /**
     * @return the jButtonSupplierAdd
     */
    public javax.swing.JButton getjButtonSupplierAdd() {
        return jButtonSupplierAdd;
    }

    /**
     * @return the jComboBoxBanchCity
     */
    public javax.swing.JComboBox getjComboBoxBanchCity() {
        return jComboBoxBanchCity;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @return the jPanel6
     */
    public javax.swing.JPanel getjPanel6() {
        return jPanel6;
    }

    /**
     * @return the jPanel7
     */
    public javax.swing.JPanel getjPanel7() {
        return jPanel7;
    }

    /**
     * @return the jPanel8
     */
    public javax.swing.JPanel getjPanel8() {
        return jPanel8;
    }

    /**
     * @return the jPanel9
     */
    public javax.swing.JPanel getjPanel9() {
        return jPanel9;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @return the jTable1
     */
    public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    /**
     * @return the jTableBranch
     */
    public javax.swing.JTable getjTableBranch() {
        return jTableBranch;
    }

    /**
     * @return the jTextFieldBranchAddress
     */
    public javax.swing.JTextField getjTextFieldBranchAddress() {
        return jTextFieldBranchAddress;
    }

    /**
     * @return the jTextFieldBranchName
     */
    public javax.swing.JTextField getjTextFieldBranchName() {
        return jTextFieldBranchName;
    }

    /**
     * @return the jTextFieldBranchSeach
     */
    public javax.swing.JTextField getjTextFieldBranchSeach() {
        return jTextFieldBranchSeach;
    }

    /**
     * @return the jTextFieldSupplierEmail
     */
    public javax.swing.JTextField getjTextFieldSupplierEmail() {
        return jTextFieldSupplierEmail;
    }

    /**
     * @return the jTextFieldSupplierName
     */
    public javax.swing.JTextField getjTextFieldSupplierName() {
        return jTextFieldSupplierName;
    }

    /**
     * @return the jTextFieldSupplierPhone
     */
    public javax.swing.JTextField getjTextFieldSupplierPhone() {
        return jTextFieldSupplierPhone;
    }

    /**
     * @param closed the closed to set
     */
    public void setClosed(boolean closed) {
        this.closed = closed;
    }

    /**
     * @param supplier the supplier to set
     */
    public void setSupplier(SupplierModel supplier) {
        this.supplier = supplier;
    }

    /**
     * @param supplierList the supplierList to set
     */
    public void setSupplierList(ArrayList<SupplierModel> supplierList) {
        this.supplierList = supplierList;
    }

    /**
     * @param branchTableModel the branchTableModel to set
     */
    public void setBranchTableModel(BranchTableModel branchTableModel) {
        this.branchTableModel = branchTableModel;
    }

    /**
     * @param jButtonBranchAdd the jButtonBranchAdd to set
     */
    public void setjButtonBranchAdd(javax.swing.JButton jButtonBranchAdd) {
        this.jButtonBranchAdd = jButtonBranchAdd;
    }

    /**
     * @param jButtonBranchDelete the jButtonBranchDelete to set
     */
    public void setjButtonBranchDelete(javax.swing.JButton jButtonBranchDelete) {
        this.jButtonBranchDelete = jButtonBranchDelete;
    }

    /**
     * @param jButtonBranchEdit the jButtonBranchEdit to set
     */
    public void setjButtonBranchEdit(javax.swing.JButton jButtonBranchEdit) {
        this.jButtonBranchEdit = jButtonBranchEdit;
    }

    /**
     * @param jButtonCancel the jButtonCancel to set
     */
    public void setjButtonCancel(javax.swing.JButton jButtonCancel) {
        this.jButtonCancel = jButtonCancel;
    }

    /**
     * @param jButtonSave the jButtonSave to set
     */
    public void setjButtonSave(javax.swing.JButton jButtonSave) {
        this.jButtonSave = jButtonSave;
    }

    /**
     * @param jButtonSupplierAdd the jButtonSupplierAdd to set
     */
    public void setjButtonSupplierAdd(javax.swing.JButton jButtonSupplierAdd) {
        this.jButtonSupplierAdd = jButtonSupplierAdd;
    }

    /**
     * @param jComboBoxBanchCity the jComboBoxBanchCity to set
     */
    public void setjComboBoxBanchCity(javax.swing.JComboBox jComboBoxBanchCity) {
        this.jComboBoxBanchCity = jComboBoxBanchCity;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @param jLabel7 the jLabel7 to set
     */
    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @param jPanel6 the jPanel6 to set
     */
    public void setjPanel6(javax.swing.JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    /**
     * @param jPanel7 the jPanel7 to set
     */
    public void setjPanel7(javax.swing.JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    /**
     * @param jPanel8 the jPanel8 to set
     */
    public void setjPanel8(javax.swing.JPanel jPanel8) {
        this.jPanel8 = jPanel8;
    }

    /**
     * @param jPanel9 the jPanel9 to set
     */
    public void setjPanel9(javax.swing.JPanel jPanel9) {
        this.jPanel9 = jPanel9;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @param jTable1 the jTable1 to set
     */
    public void setjTable1(javax.swing.JTable jTable1) {
        this.jTable1 = jTable1;
    }

    /**
     * @param jTableBranch the jTableBranch to set
     */
    public void setjTableBranch(javax.swing.JTable jTableBranch) {
        this.jTableBranch = jTableBranch;
    }

    /**
     * @param jTextFieldBranchAddress the jTextFieldBranchAddress to set
     */
    public void setjTextFieldBranchAddress(javax.swing.JTextField jTextFieldBranchAddress) {
        this.jTextFieldBranchAddress = jTextFieldBranchAddress;
    }

    /**
     * @param jTextFieldBranchName the jTextFieldBranchName to set
     */
    public void setjTextFieldBranchName(javax.swing.JTextField jTextFieldBranchName) {
        this.jTextFieldBranchName = jTextFieldBranchName;
    }

    /**
     * @param jTextFieldBranchSeach the jTextFieldBranchSeach to set
     */
    public void setjTextFieldBranchSeach(javax.swing.JTextField jTextFieldBranchSeach) {
        this.jTextFieldBranchSeach = jTextFieldBranchSeach;
    }

    /**
     * @param jTextFieldSupplierEmail the jTextFieldSupplierEmail to set
     */
    public void setjTextFieldSupplierEmail(javax.swing.JTextField jTextFieldSupplierEmail) {
        this.jTextFieldSupplierEmail = jTextFieldSupplierEmail;
    }

    /**
     * @param jTextFieldSupplierName the jTextFieldSupplierName to set
     */
    public void setjTextFieldSupplierName(javax.swing.JTextField jTextFieldSupplierName) {
        this.jTextFieldSupplierName = jTextFieldSupplierName;
    }

    /**
     * @param jTextFieldSupplierPhone the jTextFieldSupplierPhone to set
     */
    public void setjTextFieldSupplierPhone(javax.swing.JTextField jTextFieldSupplierPhone) {
        this.jTextFieldSupplierPhone = jTextFieldSupplierPhone;
    }

    private void toggleSupplierPanel(boolean b) {
        Component[] coms = jPanel9.getComponents();
        for (Component com : coms) {
            com.setEnabled(b);
        }

    }

}
