/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store;

import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author nUll
 */
public class UserView extends BaseView implements IAction {

    private JTable table;
    UserModel user;
    private UserTableModel model;

    /**
     * Creates new form UserFrame
     *
     * @param user
     */
    public UserView(UserModel user) throws Exception {
        super(user);
        initComponents();
        updateInterFaceSelf();
        this.user = user;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Users Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserView(null).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void updateInterFaceSelf() {

        table = getTable();
        ArrayList<UserModel> users = UserController.getAllUser();
        refershTable(users);
    }

    private void refershTable(ArrayList<UserModel> users) {
        try {

            model = new UserTableModel(users);
            table.setModel(model);
            if (table.isEditing()) {
                table.revalidate();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void jButtonInsertAction(ActionEvent e) {

        try {

            UserNewDialog userNewDialog = new UserNewDialog(this, rootPaneCheckingEnabled, user);
            userNewDialog.setVisible(true);

            if (userNewDialog.isClosed()) {
                int setUpdateUser = UserController.setUpdateUser(userNewDialog.getUser(), Operation.INSERT);
                updateInterFaceSelf();

            }
        } catch (Exception ex) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void jButtonUpdateAction(ActionEvent e) {

        try {

            int index = table.getSelectedRow();
            UserModel userUpdate = model.getRow(index);

            UserUpdateDialog userUpdateDialog = new UserUpdateDialog(this, rootPaneCheckingEnabled, user, userUpdate);

            userUpdateDialog.setVisible(true);

            if (userUpdateDialog.isClosed()) {
                UserController.setUpdateUser(userUpdate, Operation.UPDATE);
                updateInterFaceSelf();

            }

        } catch (Exception ex) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public void jButtonDeleteAction(ActionEvent e) {
        int[] rows = table.getSelectedRows();
        for (int index : rows) {
            UserModel selectedUser = model.getRow(index);
            UserController.setUpdateUser(selectedUser, Operation.DELETE);

        }
        updateInterFaceSelf();
    }

    @Override
    public File aExport() {
        File file = super.aExport();
        if (file != null) {
            model.exportAsPDF(file.getPath());
        }
        return null;
    }

    @Override
    public void aInsertText() {
        aChangedText();
    }

    @Override
    public void aRemovedText() {
        aChangedText();
    }

    @Override
    public void aChangedText() {
        String pattern = getTextSearch().getText();
        ArrayList<UserModel> users = UserController.getUserByLike(pattern);
        model = new UserTableModel(users);
        refershTable(users);
        table.revalidate();

    }
}
